site_name: Fundamentos en Ciencias de la Computación
site_url: https://ucudal.github.io/Fundamentos_Ciencias_Computacion_Conceptos/

repo_url: https://github.com/ucudal/Fundamentos_Ciencias_Computacion_Conceptos
repo_name: ucudal/Fundamentos_Ciencias_Computacion_Conceptos
edit_uri: edit/main/docs/

theme:
  name: material
  logo: images/logo.png

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - content.code.copy
    - content.action.edit
    - search.highlight
    - search.suggest

extra_css:
  - stylesheets/extra.css

exclude_docs: |
  _plantillas/

nav:
  - Inicio: index.md
  - Unidades:
      - 1. Ser Ing. en el s.XXI:
          - Introducción: unidad/1/readme.md
          - Syllabus, presentación del curso: unidad/1/curso/readme.md
          - Rol profesional, trayectorias y impacto ético/social: unidad/1/rol/readme.md

      - 2. Orígenes y fundamentos:
          - Introducción: unidad/2/readme.md
          - Orígenes históricos: unidad/2/origenes/readme.md
          - Sistemas de numeración: unidad/2/sist_numeracion/readme.md
          - Hardware: unidad/2/hardware/readme.md

      - 3. Sistemas y herramientas:
          - Introducción: unidad/3/readme.md
          - Shell y Bash: comandos, paths y scripts básicos: unidad/3/shell/readme.md
          - Git y Markdown: control de versiones y documentación técnica: unidad/3/git/readme.md
          - Excel: limpieza de datos, fórmulas y tablas: unidad/3/exel/readme.md
          - LaTeX: estructura básica de informes académicos: unidad/3/latex/readme.md

      - 4. Estructuras y procesos:
          - Introducción: unidad/4/readme.md
          - Estructuras de datos: unidad/4/estructuras/readme.md
          - Condición de carrera y concurrencia, Problemas clásicos de sincronización: unidad/4/condicion/readme.md

      - 5. Alfabetización en IA:
          - Introducción: unidad/5/readme.md
          - Introducción a IA y Machine Learning: unidad/5/ia/readme.md
          - IA Generativa: unidad/5/redes/readme.md

      - 6. Soluciones y trayectorias:
          - Introducción: unidad/6/readme.md
          - Análisis de una app: unidad/6/app/readme.md
          - Roles en la industria: unidad/6/roles/readme.md

  - Acerca de: acerca_de.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


